### ISSUE TITLE
Shutter angle

### ISSUE THREAD

**Issue by palemieux** [sandflow/camdkit#48]

**Comment by umathurred** [comment]
The "shutter angle" is a useful way of describing the shutter speed relative to the frame rate. This term is a conceptual relic of rotary shutters, where a disc with an angled opening would spin and let in light once per revolution to expose each frame. The larger the angle, the slower the shutter speed, all the way up to the limit of 360°, where the shutter speed could become as slow as the frame rate. At the other extreme, the shutter speed can be made arbitrarily fast by decreasing the angle.

By far the most common setting for cinema has been a shutter angle near 180°, which equates to a shutter speed near 1/48 of a second at 24 fps.

Excerpted from https://www.red.com/red-101/shutter-angle-tutorial

**Comment by umathurred** [comment]
Shutter Angle should be represented in degrees (or maybe x1000 degrees to allow fractional angles)

**Comment by palemieux** [comment]
@umathurred Please review #54
