### ISSUE TITLE
Add support for camera and lens identification information

### ISSUE THREAD

**Issue by richardssam** [sandflow/camdkit#61]
Camera Serial Number is part of the SMPTE 2065-4 spec, and does exist in Arri (as CameraSerialNumber) and Red (Camera_PIN), and I suspect for Sony Venice, its mxf/camera Attributes.

This is super useful for uniquely identifying the camera body, and its common to do lens charts recording both the camera body SN and the Lens SN, so we map cases where the camera body is producing an off center lens axis.

**Comment by palemieux** [comment]
See https://smpte.slack.com/archives/C04E88H4FNJ/p1674757096673189 re: Sony Venice

**Comment by makkbe** [comment]
I would recommend we add additional fields for camera manufacturer, model, serial number, and firmware version. These are all fields that exists in ANSI E1.59, a standard with which we should aim to be compatible.

**Comment by repentsinner** [comment]
Agreed to call out those four fields as individual records to make filtering and switching easier, and hope that the vendors use semantic versioning for their firmware version info.

**Comment by palemieux** [comment]
Below are the camera and lens identification fields:

* lens_make
* lens_model
* lens_serial_number
* lens_firmware
* camera_make
* camera_model
* camera_serial_number
* camera_firmware

**Comment by palemieux** [comment]
@repentsinner @makkbe @richardssam Please review #62

**Comment by repentsinner** [comment]
LGTM.

RED exposes user-editable SLATE_CAMERA_ID and SLATE_CAMERA_POS fields that are useful for identification, but not sure if they have parity fields from the other vendors.
