### ISSUE TITLE
Match attributes with SMPTE 2065-4 - ACES Image Container File

### ISSUE THREAD

**Issue by richardssam** [sandflow/camdkit#63]
Attribute names here are a "_" format, rather than the camelCase format that is used for existing SMPTE 2065-4 spec.

Here is a spreadsheet that matches the SMPTE attributes against, the OSVP VFX parameters:

https://docs.google.com/spreadsheets/d/1z75TXNsh437NIOQXQJ2e0gfv5cmu3_E_/edit#gid=1127003645

 I'm happy to make a patch request for this, if this makes sense.

**Comment by palemieux** [comment]
@richardssam The canonical names are set in `model.py`: https://github.com/sandflow/camdkit/blob/77feec72a1da16b0a6177cc5570fda44812c33c4/src/main/python/camdkit/model.py#L70
