### ISSUE TITLE
Spreadsheet uses "firmware version," but CAMDKIT just says "firmware." 

### ISSUE THREAD

**Issue by j-helman** [sandflow/camdkit#75]
Which do we want?

**Comment by repentsinner** [comment]
IMO `firmware version` is preferred, presumably firmware could eventually be a binary blob of firmware.

**Comment by j-helman** [comment]
Pull request #70 would resolve this.

**Comment by palemieux** [comment]
Fixed at 6b6f3621cead2fb4b119fa6c38dd0c5ed5f2426e
